---
- name: Switch to Bitwarden EU servers
  command: /usr/local/bin/bw config server https://vault.bitwarden.eu
  delegate_to: localhost
  when: vault_status != "unlocked"

- name: Login to Bitwarden with API key
  command: /usr/local/bin/bw login --apikey
  environment:
    BW_CLIENTID: "{{ bw_client_id }}"
    BW_CLIENTSECRET: "{{ bw_client_secret }}"
  register: login_result
  no_log: true
  delegate_to: localhost
  when: vault_status != "unlocked" 
  failed_when: >
      login_result.rc != 0 and "You are already logged in" not in login_result.stderr

- name: Start Bitwarden server
  command: /usr/local/bin/bw serve
  async: 600
  poll: 0
  register: bw_server
  delegate_to: localhost
  when: vault_status != "unlocked"

- name: Wait for API to be reachable
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/API_requests/ensure_api_working.yaml"

- name: Unlock vault via API
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/API_requests/unlock_vault.yaml"
  when: vault_status != "unlocked"

- name: Set other facts
  set_fact:
    workflow_id: "{{ controller_workflow_job_id | default('manual') }}"
    start_timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}"
    cacheable: false
  delegate_to: localhost

- name: Sync vault via API
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/API_requests/sync_vault.yaml"