---
# tasks file for awx.bitwarden_password_manager

- name: Set initial vault status
  set_fact:
    vault_status: "not_ready"

- name: Check vault status
  include_tasks: "{{ role_path }}/API_requests/ensure_vault_unlocked.yaml"
  
- name: Setup API if needed
  include_tasks: api_setup.yaml
  when: vault_status != "unlocked"

- name: BW API CALL - Read Bitwarden entries
  include_tasks: "{{ role_path }}/API_requests/get_list_entries.yaml"
  when: operation == 'read'

- name: BW API CALL - Update Bitwarden entry
  include_tasks: "{{ role_path }}/API_requests/update_entry.yaml"
  when: operation == 'update'

- name: BW API CALL - Create Bitwarden entry
  include_tasks: "{{ role_path }}/API_requests/create_entry.yaml"
  when: operation == 'create'

- name: BW API CALL - Delete Bitwarden entry #TODO: Not implemented yet
  include_tasks: "{{ role_path }}/API_requests/delete_entry.yaml"
  when: operation == 'delete'