---
# tasks file for awx.bitwarden_password_manager

- name: Vault status check
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/API_requests/ensure_vault_unlocked.yaml"
  when: vault_status is defined

- name: Set initial vault status
  set_fact:
    vault_status: "locked"
  when: vault_status is not defined

- name: Setup API if needed
  include_tasks: api_setup.yaml

- name: BW API CALL - Get password for one entry
  include_tasks: "{{ role_path }}/API_requests/get_password.yaml"
  when: operation == 'read_password'

- name: BW API CALL - Read all Bitwarden entries
  include_tasks: "{{ role_path }}/API_requests/get_list_entries.yaml"
  when: operation == 'read_collection'

- name: BW API CALL - Update Bitwarden entry
  include_tasks: "{{ role_path }}/API_requests/update_entry.yaml"
  when: operation == 'update'

- name: BW API CALL - Create Bitwarden entry
  include_tasks: "{{ role_path }}/API_requests/create_entry.yaml"
  when: operation == 'create'

- name: BW API CALL - Delete Bitwarden entry #TODO: Not implemented yet
  include_tasks: "{{ role_path }}/API_requests/delete_entry.yaml"
  when: operation == 'delete'