---
# tasks file for awx.bitwarden_password_manager

- name: Setup API
  include_tasks:
    file: api_setup.yaml

- name: Password rotation tasks
  include_tasks: rotate_passwords.yaml
  when: operation == 'rotate'

- name: Create Bitwarden entry
  include_tasks: create_entry.yaml
  when: operation == 'create'

- name: Delete Bitwarden entry
  include_tasks: delete_entry.yaml
  when: operation == 'delete'