---
- name: Generate new password for "{{ vm_name }}" == "{{ target_name }}"
  set_fact:
    new_password: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters,digits') }}"
    old_password: "{{ old_password | password_hash('sha512') }}"
  delegate_to: localhost
  no_log: true

- name: Hash password for "{{ vm_name }}"
  set_fact:
    hashed_new_password: "{{ new_password | password_hash('sha512') }}"  
  delegate_to: localhost
  no_log: true

- name: Change root password
  ansible.builtin.user:
    name: root
    password: "{{ hashed_new_password }}"
    update_password: always
  become: true
  register: password_change
  no_log: true

- name: Test new password 
  ansible.builtin.shell: |
    echo "{{ new_password }}" | su -c "whoami" "{{ login }}"
  register: test_result
  become_user: "{{ login }}"
  ignore_errors: true
  no_log: true

- name: Revert password if test failed
  ansible.builtin.user:
    name: root
    password: "{{ old_password }}"
    update_password: always
  become: true
  when: test_result.rc != 0 or test_result.stdout != "root"
  no_log: true

- name: Push new password to Bitwarden
  ansible.builtin.include_tasks:
    file: api_requests/update_entry.yaml