---
- name: Retrieve entries from vault
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/API_requests/get_list_entries.yaml"

- name: Update Bitwarden entries
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/API_requests/update_entry.yaml"
  vars:
    entry_id: "{{ item.id }}"
    target_name: "{{ item.fields | selectattr('name', 'equalto', 'VM Name') | map(attribute='value') | first }}"
  loop: "{{ netbox_linux_root_entries.json.data.data }}"
  no_log: true
  when: target_name | lower == inventory_hostname | lower