---
- name: Retrieve old passwords
  ansible.builtin.include_tasks:
    file: api_requests/get_list_entries.yml

- name: Extract credentials, update Linux servers, update Bitwarden entry
  ansible.builtin.include_tasks: password_change.yml
  vars:
    entry_id: "{{ item.id }}"
    target_name: "{{ item.fields | selectattr('name', 'equalto', 'VM Name') | map(attribute='value') | first }}"
    login: "{{ item.login.username }}"
    old_password: "{{ item.login.password }}"
  loop: "{{ netbox_linux_root_entries.json.data.data }}"
  no_log: true
  when: target_name | lower == inventory_hostname | lower